### ISSUE TITLE
thumbnail mode THUMBNAIL_INSET not centered

### ISSUE THREAD

**Issue by krzysztofgal** [yiisoft/yii2-imagine#14]
I'am trying to create thumbnails, and I need 'inset' mode, images are always at top left corner of thumbnails, and there is no way to make them centered. In 'outbound' mode images are centered.

**Comment by Demyan112rv** [comment]
I have same problem after this commit:
[https://github.com/yiisoft/yii2-imagine/commit/d87e6a0d1adfd6fa5ef49c18228b2fc9bca04299](url)

**Comment by cebe** [comment]
@samdark it was committed by you, can you check it?

**Comment by samdark** [comment]
@Demyan112rv are you using inset mode?

**Comment by Demyan112rv** [comment]
@samdark yes. My example:

` $thumb = Image::thumbnail($this->getImageFullPath(), 600, 400, ManipulatorInterface::THUMBNAIL_INSET);
$thumb->save($this->getThumbFullPath());`

**Comment by Demyan112rv** [comment]
@samdark When i revert to 2.0.3 version it's working good. Images creating are centered.

**Comment by samdark** [comment]
:( Can you help solving it in the current code?
