### ISSUE TITLE
How can I set and use just of `Gd2` library?

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii2-imagine#16]
In default, use of first supported item of `$driver` array:
`public static $driver = [self::DRIVER_GMAGICK, self::DRIVER_IMAGICK, self::DRIVER_GD2];`
How can I set and use just of `Gd2` library?

**Comment by cebe** [comment]
`\yii\imagine\Image::$driver = [\yii\imagine\Image::DRIVER_GD2];` ?
