### ISSUE TITLE
"imagine/imagine": "0.5.*" is deprecated for imagic

### ISSUE THREAD

**Issue by KUbo0** [yiisoft/yii2-imagine#17]
PHP Fatal error:  Undefined class constant 'COLOR_OPACITY' in /vendor/imagine/imagine/lib/Imagine/Imagick/Image.php on line 677

ImageMagick have updated 3 days ago
yii2-image using Imagine 0.5.0 (2013), most recent 0.6.3 (2015-09-19) and it dosen't use COLOR_OPACITY const.

when I try to update imagine/imagine to  ^0.6.3 by composer it says:  Problem 1
    - yiisoft/yii2-imagine 2.0.3 requires imagine/imagine 0.5.\* -> satisfiable by imagine/imagine[0.5.x-dev, v0.5.0] but these conflict with your requirements or minimum-stability.

| Q | A |
| --- | --- |
| Yii vesion | 2.0.8 |
| PHP version | 5.5.17 |
| Operating system | Linux |
| imagick module version | 3.4.3RC1 |
| Imagick using ImageMagick library version | ImageMagick 7.0.2-1 Q16 x86_64 2016-06-23 |

**Comment by klimov-paul** [comment]
This should be reported to https://github.com/avalanche123/Imagine project.
There is no way we can fix it here.

**Comment by KUbo0** [comment]
thought you can fix composer.json require section

**Comment by samdark** [comment]
Going to update dependencies with 2.1.0 release. This one may be fixed then. Since there's nothing else we can do, closing.
