### ISSUE TITLE
Driver imagick - whiter shade of thumbnail

### ISSUE THREAD

**Issue by pabloneruda1** [yiisoft/yii2-imagine#21]
`Image::$driver = 'imagick';`
`Image::thumbnail($filePath, 300, 300, ManipulatorInterface::THUMBNAIL_INSET)->save($targetFilePath);`

This code create whiter shade of thumbnail.
With driver GD2 is all OK. Bug in imagick?

Yii vesion 2.0.10
PHP version 5.4
Source image: http://www.torriacars.cz/data/imgauto/18/0/5901207901.jpg

**Comment by samdark** [comment]
Probably it is. Going to release 2.1.0 soon. It could fix it. Please recheck.

**Comment by samdark** [comment]
2.1.0 was released. @pabloneruda1 would you please re-check if your problem is still there?

**Comment by pabloneruda1** [comment]
Problem is still there

**Comment by pabloneruda1** [comment]
My solution to this issue:
1) The original image save as PNG (with original dimensions)
2) The thumbnail is generated from PNG
And thumbnail is OK
Perhaps this problem affects only JPG images from Adobe Photoshop, but WHY?

**Comment by samdark** [comment]
Color profiles?

**Comment by pabloneruda1** [comment]
Color profile detected via Imagick is:
array ( 0 => '8bim', 1 => 'exif', 2 => 'icc', 3 => 'iptc', 4 => 'xmp', )

I do not know, it's OK or not?

**Comment by samdark** [comment]
I've meant that imagick may actually read and use color profiles when doing transformation (or other way around: GD does it, IM does not). ICC is color correction which may be the case. Try stripping down all the metadata from image and then trying GD/IM. If it changes anything then color profiles are the case.
