### ISSUE TITLE
FILL option for thumbnail generation

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2-imagine#22]
Thumbnail method is not doing exactly what I would want it to.

I would need a FILL option as described there: http://a32.me/2012/06/scale-images-to-fit-fill-bounding-box-in-php-using-gd/

As in my usecase I don't need all the images to be the same size but I do need them to fit in max width and height boundaries. And without cropping .

**Comment by dynasource** [comment]
@Renkas, can you post some code to show your usecase?

**Comment by Renkas** [comment]
I don't really get what code do you want to see? This usecase is more of a visual thing as current `thumbnail()` method creates fixed with/height box and fits resized image to the center of it or crops to the widest edge. But in my usecase I would like to get a thumbnail that has no fixed with/height but a maximum with/height. I think this is quite well documented on the link I gave.

Current implementation supports FIT mode from that description. I would like to get a FILL mode added to the method. Or it could also be totally different method. Maybe name it `resize()` or something like that.

**Comment by dynasource** [comment]
I would be way more helpful for us if you visualize your request in code, instead of having to visit external websites because of too short problem descriptions.

**Comment by Renkas** [comment]
I don't really get it what you want/need from me now. :) Is something still unclear from the request? What exactly?

As far as I see only thing missing is full implementation. Everything else is already written. And there is even full implementation in GD and visual examples behind that link. I'm not going to copy other peoples work/examples/code here when it can easily be viewed in it's original environment.

**Comment by dynasource** [comment]
I cannot be more clear than this ;). Regarding myexpectations? Please feel free to do a PR to cover your usecase. We are willing to review & merge.
