### ISSUE TITLE
Image::thumbnail with Upscaling?

### ISSUE THREAD

**Issue by kasoft** [yiisoft/yii2-imagine#28]
### What steps will reproduce the problem?
Use a Image smaller than 120x120 and create a Thumbnail with Box Option

Image::thumbnail('@webroot/img/test-image.jpg', 120, 120, ImageInterface::THUMBNAIL_INSET)
->save(Yii::getAlias('@runtime/thumb-test-image.jpg'), ['quality' => 50]);

### What's expected?
The smaller Image should be placed inside the Box 120x120

### What do you get instead?
A Thumbnail with the original size. Maybe this is intened, but if you specify the size, you expect the Image to be upscaled

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| Image Version | 2.1.0
| PHP version      | 5.6.27
| Operating system | Mac/Linux

**Comment by Demak** [comment]
It seems like by design image will not be upscaled, but in documentation there is a misleading sentence:
> If both dimensions are specified, resulting thumbnail would be exactly the width and height specified. How it's achieved depends on the mode.
which implies that image of any size will be always resized/cropped to fit specified sizes.

**Comment by MGerasimchuk** [comment]
So sad about abandoned PR https://github.com/yiisoft/yii2-imagine/pull/33
((

Any news about fixes of this issue?

**Comment by samdark** [comment]
> Any news about fixes of this issue?

No, more pressing matters too my time. If you have time you can prepare a pull request taking comments left there into account. I'll review/merge it.

**Comment by yuniorsk** [comment]
There's new flag `ImageInterface::THUMBNAIL_FLAG_UPSCALE` in Imagine since version 1.0.0 but it was introduces as a breaking change [see here](https://github.com/avalanche123/Imagine/blob/develop/CHANGELOG.md)

> BREAKING CHANGE the $mode argument has been renamed to $settings, and it's now an integer (but old string values are accepted for backward compatibility). In this case the ManipulatorInterface constants THUMBNAIL_INSET, THUMBNAIL_OUTBOUND were changed from string values to integers.

Problem is this was not reflected in this codebase and this line could cause problems
https://github.com/yiisoft/yii2-imagine/blob/21d3df6f100410a40a163f849d311faf138b88b8/src/BaseImage.php#L231

I can make PR, but that would require dropping support for older versions of Imagine. 

What do you think?

**Comment by samdark** [comment]
There are no outstanding issues with current version so I think we can release 2.3.0 or even 3.0.0 with some breaking changes.

**Comment by cuiyun97** [comment]
Exception 'Imagine\Exception\RuntimeException' with message 'Unable to open image /cyzz/temp/liao-wx/web/uploads/book/20200823/c826fd60112b70dbf5f19bdca3bc4ede.jpg' 

in /cyzz/temp/liao-wx/vendor/imagine/imagine/src/Gd/Imagine.php:95
