### ISSUE TITLE
Call to undefined method yii\imagine\Image::resize()

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2-imagine#29]
![Uploading Снимок экрана (23).png…]()

**Comment by rumatakira** [comment]
![23](https://cloud.githubusercontent.com/assets/16696651/21561050/9c337b14-ce67-11e6-9330-0dc9e1aca75c.png)

**Comment by rumatakira** [comment]
\yii\imagine\Image::frame() working normally by the way.

**Comment by samdark** [comment]
resize() method isn't part of any release yet.

**Comment by r4cdv** [comment]
If there is no new version of the framework, update at least the imagine in which there will be a method of resizing the image with the proportion

**Comment by RobinJespersen** [comment]
+1
