### ISSUE TITLE
Thumbnail method creates rectangle

### ISSUE THREAD

**Issue by ps202** [yiisoft/yii2-imagine#3]
Image::thumbnail($path, 100, 100)->save($thumbnail, ['quality' => 50]);

should create an image maintaining aspect ratio, but it does not.
It creates a rectangular - 100x100 px - image.

**Comment by cebe** [comment]
according to the docs the output will be 100x100 but the image you see keeps aspect ratio. if it does not fit the background may be white in the parts that does not fit dependend on the last parameter.

**Comment by ps202** [comment]
Yes, according to the docs it should be like that.
But it isn't. Maybe I do something wrong...
Here is the complete code:
    use yii\imagine\Image;
    $model = new Album();
        $picture = new Picture();

        if ($model->load(Yii::$app->request->post()) && $picture->load(Yii::$app->request->post())) {
            $model->save();
            if ($picture->file) {
			$picture->file = UploadedFile::getInstances($picture, 'file');
                foreach ($picture->file as $file) {
				$savedname = uniqid() . '.' . $file->extension;
				$path = $this->uploadDirectory . DIRECTORY_SEPARATOR . $savedname;
				$coverimage = $this->coverDirectory . DIRECTORY_SEPARATOR . $savedname;
				$thumbnail = $this->thumbnailDirectory . DIRECTORY_SEPARATOR . $savedname;
                    $file->saveAs($path);
                    Image::thumbnail($path, 1200, 1200)->save($path, ['quality' => 90]);
                    Image::thumbnail($path, 400, 400)->save($coverimage, ['quality' => 80]);
                    Image::thumbnail($path, 100, 100)->save($thumbnail, ['quality' => 50]);
                    $pic = new Picture();
                    $pic->albumid = $model->id;
                    $pic->filename = $savedname;
                    $pic->save(false);
                }
			return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'picture' => $picture,
            ]);
        }
    }

**Comment by ps202** [comment]
Using the thumbnail method with imagines own functions, it works:

    use Imagine\Gd;
    use Imagine\Image\Box;
    use Imagine\Image\BoxInterface;

    ...

    $photo = $imagine->open($path);
    $photo->thumbnail(new Box(1200, 1200))->save($path, ['quality' => 90]);
