### ISSUE TITLE
The script that uses the "Imagine" dying without any error messages.

### ISSUE THREAD

**Issue by robotE13** [yiisoft/yii2-imagine#30]
Simply create new Imagine object then load image from string:

`$fileContents = file_get_contents('http://ed-elaboration.com/files/previews/120_main_seliger.jpg');`
`$image = yii\imagine\Image::getImagine()->load($fileContents);`
`echo ' >> Loaded';`

And the script will shut down without throw Exception. Message 'Loaded' doesn't appear.

Some files can be loaded but give same behavior when i'm trying crop it:
`yii\imagine\Image::thumbnail($image, ....`

That happening with some files. A link to the file that caused this error you can see in code above.

If I directly using the "Imagick" or GD, all files are processed without any errors.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion      |  2.0.10
| PHP version      | 5.6.26-1~dotdeb+7.1 (cli)
| Operating system | Debian GNU/Linux 7.11 (wheezy)

**Comment by samdark** [comment]
Is that exact URL in the code to reproduce the issue?

**Comment by robotE13** [comment]
This is a link to the file that is causing the error when i try crop it via Image::thumbnail().
URL to reproduce the problem is not exist because the script is a console command.

**Comment by samdark** [comment]
Cannot reproduce the issue. Successfully loaded and thumbnailed image from your URL.

**Comment by robotE13** [comment]
The problem is most likely in the specific server settings. On the local machine and on the other server the process running correct. But here it is on the server where the image, the script terminates abnormally without any messages. When calling Image::thumbnail().
If necessary, you can contact me via Skype. robotg13

**Comment by samdark** [comment]
I can't reproduce it so I can't dig into it. If you'll find out the reason, let me know by commenting in this issue.
