### ISSUE TITLE
Error while blur an image.

### ISSUE THREAD

**Issue by RussellSk** [yiisoft/yii2-imagine#31]
Try to use blur effect. 

use yii\imagine\Image;

```
...
Image::getImagine()
                        ->open($original_image)
                        ->effects()->blur(3)
                        ->save($this->_uploads_directory . '/'. $altPath);
...
```

But receive next error:
`imagefilter(): supplied resource is not a valid Image resource`

`if (false === imagefilter($this->resource, IMG_FILTER_GAUSSIAN_BLUR))`

Is it my usage fail or module issue?

**Comment by samdark** [comment]
Can not reproduce it. Probably method chaining is used wrong. That's how it works well:

```php
$image = ImagineImage::getImagine()->open($original_image);
$image->effects()->blur(3);
$image->save($this->_uploads_directory . '/'. $altPath);
```
