### ISSUE TITLE
problem with persian characters

### ISSUE THREAD

**Issue by hmkhafan** [yiisoft/yii2-imagine#34]
i have a project with yii2
and i want to write customer name on a membership_cart that saved in image formt.
the characters saved successfully but it reversed. for example instead of "عباس" it save "س اب ع"

**Comment by samdark** [comment]
It is tricky in the low level libraries as well. No good RTL support. See:

http://stackoverflow.com/questions/24092369/write-rtl-arabic-text-to-image-with-php

**Comment by samdark** [comment]
If you'll find a solution please let me know if that's generic enough to be adopted by Yii somehow.
