### ISSUE TITLE
BaseImage misprints

### ISSUE THREAD

**Issue by Svyatoslav-S** [yiisoft/yii2-imagine#35]
Hello! I've found two misprints.

BaseImage.php lines 251 and 254 (function thumbnail)

$startX = ceil($width - $size->getWidth()) / 2; 
...
$startY = ceil($height - $size->getHeight()) / 2;

I think, you need move closing brackets to end of expressions.

$startX = ceil(($width - $size->getWidth()) / 2); 
...
$startY = ceil(($height - $size->getHeight()) / 2);

**Comment by samdark** [comment]
Yes. Seems it was meant to be what you're suggesting.
