### ISSUE TITLE
Save operation failed  Caused by: ImagickException

### ISSUE THREAD

**Issue by hawkcraw** [yiisoft/yii2-imagine#36]
Imagine\Exception\RuntimeException

Save operation failed
↵
Caused by: ImagickException

UnableToOpenBlob `uploads/products/xxxxx/thumbnail/65x65/6.jpg': No such file or directory @ error/blob.c/OpenBlob/2702

**Comment by samdark** [comment]
Looks like you don't have such file.

**Comment by hawkcraw** [comment]
if I use GD lib,It works
---------------------------------
I change the file: yii2-imagine/BaseImage.php
public static $driver = [self::DRIVER_GMAGICK, self::DRIVER_GD2, self::DRIVER_IMAGICK];

**Comment by igorveremsky** [comment]
@hawkcraw problem can be connected with incorrect install Imagick. For example, you don`t have Imagick proccessing binary files for png files. Can you send here phpinfo() with imagick options? It looks like: 
![screenshot_139](https://user-images.githubusercontent.com/13087365/36195285-b2a24978-1175-11e8-90f5-265af40e9497.png)

**Comment by klimov-paul** [comment]
Closed since there is no coherit information to reproduce the issue.
