### ISSUE TITLE
README needs update?

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2-imagine#38]
### What steps will reproduce the problem?
Fallow the README.md and add `"yiisoft/yii2-imagine": "~2.0.0"`

### What's expected?
Latest version of extension

### What do you get instead?
Old 2.0.* version

so, README.md should says: `"yiisoft/yii2-imagine": "^2.0.0",` or sth?

**Comment by cebe** [comment]
fixed, thanks!
