### ISSUE TITLE
Are there any plans to update the dependencies?

### ISSUE THREAD

**Issue by igorekpro** [yiisoft/yii2-imagine#40]
I'm working on website optimization for Google Page Speed, in particular on optimizing images.

For example, this works for jpg:

`Image::getImagine()->open($filePath)->strip()->save($filePath, ['quality' => 85]);`

but png is almost not compressed.

In Imagine version 0.7 has options `png_compression_level` and `png_compression_filter` that should help.

**Comment by samdark** [comment]
Yes. There's such plan.

**Comment by igorekpro** [comment]
@samdark thanks, I'll wait.

**Comment by samdark** [comment]
#32

**Comment by davidhirtz** [comment]
Upgrading the dependencies would also take care of this annoying issue:
https://github.com/avalanche123/Imagine/commit/968115fd4bae82135c20ab1b2b66542585c37389#diff-746aa343aefa8eb159eeeaebf95cbb67

**Comment by klimov-paul** [comment]
Duplicates #46
