### ISSUE TITLE
method resize with proportions

### ISSUE THREAD

**Issue by r4cdv** [yiisoft/yii2-imagine#41]
### What steps will reproduce the problem?
http://stuff.cebe.cc/yii2docs-ru/yii-imagine-baseimage.html#resize%28%29-detail

```
Image::resize(Yii::getAlias('@webroot'.'/img/gallery/original/' . $file), 300, 
300, true, true)
->save(getAlias('@webroot'.'/img/gallery/300x300/' . $file), ['quality' => 80])
```

how do I properly use this method?

I need to resize the image and save the result.
If the image is larger - it needs to be reduced according to its proportions.
If the image is smaller - it needs to be increased according to the proportions

### What's expected?
proportionally reduced or enlarged image
### What do you get instead?

> Error
> Call to undefined method yii\imagine\Image::resize()

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.13-dev
| PHP version      |7.1.0
| Operating system |windows 10

**Comment by imitronov** [comment]
https://github.com/yiisoft/yii2-imagine/blob/master/BaseImage.php#L279
Resize - since v2.1.1
edit composer.json to "yiisoft/yii2-imagine": "dev-master" and run "composer update" to fix
