### ISSUE TITLE
Can't create thumbnail from binary string

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2-imagine#43]
### What steps will reproduce the problem?
````php
$data = base64_decode($base64data);
yii\imagine\Image::Thumbnail((yii\imagine\Image::getImagine())->load($data), $somewidth, $someheight);
````
### What's expected?
Expecting to create thumbnail from base64 decoded string.

### What do you get instead?
````
InvalidParamException('File should be either ImageInterface, resource or a string containing file path.');
````
in file `/vendor/yiisoft/yii2-imagine/BaseImage.php` line 147

### Additional info
Another problem I see in that same function, you check whether the image is instance of `ImageInterface`, but I think you must check for `ImagineInterface` instead, though this doesn't help with my case.

**Comment by dmirogin** [comment]
try this
```php
 Image::Thumbnail((Image::getImagine()->load(file_get_contents('data:image/jpeg;base64,/9j/4AAQS...'))), 100, 200)
```

**Comment by armpogart** [comment]
@dmirogin 
It will probably work, but `Imagine` must natively work with binary through [load](http://imagine.readthedocs.io/en/latest/_static/API/Imagine/Image/ImagineInterface.html#method_load) method.

**Comment by klimov-paul** [comment]
This wontfix.
We can not magically separate string, which is a file path from the string is a binary data.
You should create `Imagine\Image\ImageInterface` instance manually for this case as @dmirogin suggets.

**Comment by armpogart** [comment]
Strange, but I've tried it again, and the code I mentioned actually works as expected (leaving it here for others reference):
```php
yii\imagine\Image::Thumbnail(yii\imagine\Image::getImagine()->load($binaryData), $somewidth, $someheight);
```
