### ISSUE TITLE
update imagine/imagine version to 0.7?

### ISSUE THREAD

**Issue by sniper888** [yiisoft/yii2-imagine#46]
update imagine/imagine version to 0.7?

**Comment by webspec2012** [comment]
да, очень ждём!

**Comment by ricpelo** [comment]
Any news about this issue? Is there an ETA for 2.1.1?

**Comment by klimov-paul** [comment]
Resolved by commit 5e525648c459bca5ae22b354b62f3c6571fe4768

**Comment by ricpelo** [comment]
Thank you, @klimov-paul !
