### ISSUE TITLE
Class 'Imagine\\Image\\ManipulatorInterface' not found

### ISSUE THREAD

**Issue by denghp** [yiisoft/yii2-imagine#6]
I use composer to install the yii2-imagine, class dependent imagine/imagine is also installed, how is the not found exception

{"name":"PHP Fatal Error","message":"Class 'Imagine\\Image\\ManipulatorInterface' not found","code":1,"type":"yii\\base\\ErrorException","file":"/home/denghp/workspace/yii2-demo/vendor/yiisoft/yii2-imagine/BaseImage.php","line":149,"stack-trace":["#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()","#1 {main}"]}

**Comment by cebe** [comment]
have you included the composer autoloader in your project? should be included in the index.php file.
