### ISSUE TITLE
php 7.3.6 segmentation fault

### ISSUE THREAD

**Issue by dficonfont** [yiisoft/yii2-imagine#60]
`Image::thumbnail($url, 250 , 352);`

        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "yiisoft/yii2-imagine": "~2.2.0",

Older versions of PHP won't have this problem

**Comment by samdark** [comment]
Are these important?

```
"yiisoft/yii2-bootstrap": "~2.0.0",
"yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
```
