### ISSUE TITLE
Update or copy image and preserve exif meta data

### ISSUE THREAD

**Issue by HardwareCat** [yiisoft/yii2-imagine#63]
How does the Yii2 Imagine handle exif data in an updated or new image?

`Image::getImagine()->open($image)->save($output, ['quality' => 50]);`

exif meta data will disappear, does not save the exif meta data of the $image

`$exif = exif_read_data($image, 0, true);`
If you can't update image, how can I add it $exif?

a new setter would solve the problem

`Image::getImagine()->open($image)->setExif($exif)->save($output, ['quality' => 50]);`

| Q                | A
| ---------------- | ---
| Yii version      | Yii2
| Imagine version  | newest

**Comment by samdark** [comment]
Thanks for reporting. I have one extra question.

Which adapter do you use? If it's GD and not imagick then it's normal behavior as GD does not deal with EXIF at all. Thus re-saving image with it won't have any metadata and it worth switching to imagick or gmagick which would likely to fix the issue and, as well, improve performance.

Underlying [Imagine library](https://github.com/avalanche123/Imagine) [does not have EXIF writing support](https://github.com/avalanche123/Imagine/issues/330) and it's not planned to add it so while implementing `setExif()` should be possible from our side, we'd like to avoid it.
