### ISSUE TITLE
ExifMetadataReader::extractFromFile() does not return EXIF data

### ISSUE THREAD

**Issue by stevekr** [yiisoft/yii2-imagine#64]
### What steps will reproduce the problem?
`(new ExifMetadataReader())->readFile($path)`

### What's expected?
Array populated with EXIF data. `exif_read_data($path, null, true, false)` works fine.

### What do you get instead?
Array with only 'uri' and 'filepath'.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| Imagine version  | 2.2.0
| PHP version      | 7.3.11
| Operating system | Linux

**Comment by samdark** [comment]
Should be reported to https://github.com/avalanche123/Imagine
