### ISSUE TITLE
Please update to imagine 0.6.2

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2-imagine#7]
https://github.com/avalanche123/Imagine/releases/tag/0.6.2

**Comment by cebe** [comment]
see #4

**Comment by jacmoe** [comment]
If this is already done, perhaps this could be closed ? :)

**Comment by SilverFire** [comment]
No, it's not done.

**Comment by samdark** [comment]
We've sticked to 0.5. I think we can release 2.1.0 of this ext while upgrating imagine...

**Comment by royalrex** [comment]
Any plans of soon upgrading to imagine 0.6.x ? Really want to use the metadata feature added in version 0.6.0

**Comment by cnzhangxl** [comment]
when i use gmagick,thowException"alpha transparency not implemented", i see  imagine 0.6.2 no this bug,why not update to  imagine 0.6.2???

**Comment by samdark** [comment]
Requirement will be raised in 2.1.0.

**Comment by nadar** [comment]
Is there something the community could help to make a 2.1.x release? What are the plans, problems, ideas? To raise the requirement of imagine to 0.6.x is absolut necessary.

**Comment by nadar** [comment]
@thejahweh I just created a 0.6.x compatible version of Yii2-Imagine.

https://github.com/nadar/yii2-imagine

```
"nadar/yii2-imagine": "^2.0@dev",
```

**Comment by samdark** [comment]
The code is there. Going to tag and write a release announcement a bit later.

**Comment by nadar** [comment]
@samdark Any news about releasing version 2.1.0?

**Comment by samdark** [comment]
Working on it.
